baseURL = "https://blog.mdeliu.com"
title = "blog.mdeliu.com"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Personal blog of Musano Deliu. Mostly about topics in the IT resp. technical area."
  copyright = ""
  dark = "auto"
  highlight = true

 [menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "tags"
    url = "/tags/"
    weight = 2
    
[[menu.main]]
    identifier = "impressum"
    name = "Impressum"
    title = "impressum"
    url = "/impressum/"
    weight = 3

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
